=== unovue/shadcn-vue/apps/www/src/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "style": {
      "type": "string",
      "enum": ["default", "new-york"]
    },
    "typescript": {
      "type": "boolean",
      "default": true
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "string"
        },
        "css": {
          "type": "string"
        },
        "baseColor": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean",
          "default": true
        }
      },
      "required": ["config", "css", "baseColor", "cssVariables"]
    },
    "framework": {
      "type": "string",
      "enum": ["nuxt", "vite", "laravel", "astro"],
      "default": "vite"
    },
    "aliases": {
      "type": "object",
      "properties": {
        "utils": {
          "type": "string"
        },
        "components": {
          "type": "string"
        }
      },
      "required": ["utils", "components"]
    }
  },
  "required": ["style", "tailwind", "aliases"]
}

=== unovue/shadcn-vue/packages/module/playground/components.json
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "default",
  "typescript": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "assets/css/tailwind.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "framework": "nuxt",
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
